# API ROUTING OVERVIEW 
frontend/curl -> nginx -> internal_microservices :

# CHOSEN BASE URL
-> api_network_base_url: http://redjungle.area51

# CHOSEN BASE URL
-> identity_microservice: 9011 / DB{7011} = [v1]
-> hierarchy_microservice: 9012 / DB{7012} = [v2]
-> auth_microservice: 9013 / DB{7013} = [v3]
-> note_microservice: 9014 / DB{7014} = [v4]

# each call to the server goes through identity to confirm user_id & session_id match

# URI PATHS
-> [v1 {/identity} ] = identity:
{ get/post } = [ /user, /session ]

-> [v2 {/hierarchy} ] = hierarchy:
{ get/post } = [ /group, /folder, /note ]

-> [v3 {/auth} ] = auth:
{ get/post } = [ /group, /folder, /note ]

-> [v4 {/content} ] = content:
{ get/post } = [ /content ]

# DB SCHEMATICS [service -> service {ACL} ] => For cascading CRUD funtions... Later
# -> hierarchy 
db_group_architecture = {
        'group_id':"",
        'group_name':"",
        'group_owner':"",
        'visibility':""
}
db_folder_architecture = {
        'folder_id':"",
        'group_id':"",
        'folder_name':"",
        'visibility':""
}
db_note_architecture = {
        'note_id':"",
        'folder_id':"",
        'note_name':"",
        'note_owner':"",
        'content_id':"",
        'visibility':""
}
# -> auth 
db_group_auth_architecture = {
        'group_id':"",
        'members':""
}
db_folder_auth_architecture = {
        'folder_id':"",
        'group_id':"",
        'admin_id':""
        'members':""
}
db_note_auth_architecture = {
        'note_id':"",
        'group_id':"",
        'folder_id':"",
        'collaborators':""
}
# -> content 
db_content = {
        'content_id':"",
        'note_id':"",
        'group_id':"",
        'folder_id':"",
        'contents':""
}
# -> identity
db_users = {
        'email':"",
        'user_id':"",
        'hashcode':"",
}
db_session_ids = {
        'session_id':"",
        'user_id':"",
        'status':"active/expired"
}




