##################################################

api_network_base_url: http://redjungle-00.lab

##################################################

traffic_gateway_microservice: 9011

identity_microservice: 9012

hierarchy_record_microservice: 9013

member_relation_microservice: 9014

note_microservice: 9015


##################################################








