services:
  webapp_hierarchy_endpoint:
    build: .
    ports:
      - "9013:9013"
    volumes:
      - ./app:/app
      - /requirements.txt

    command:
      [
        "uvicorn",   
        "main_hierarchy_record:app",   
        "--reload",
        "--port",   
        "9013",   
        "--host",   
        "0.0.0.0"
      ]





